[package]
name = "cid"
version = "0.2.0"
description = "CID in rust"
homepage = "https://github.com/ipld/rust-cid"
authors = ["Friedel Ziegelmayer <dignifiedquire@gmail.com>"]

keywords = ["ipld", "ipfs", "cid", "multihash"]

license = "MIT"

readme = "README.md"

[dependencies]
multihash = "~0.5.0"
multibase = "~0.6.0"
integer-encoding = "~1.0.3"
