[package]
name = "cid"
version = "0.1.0"
description = "CID in rust"
homepage = "https://github.com/ipld/rust-cid"
authors = ["Friedel Ziegelmayer <dignifiedquire@gmail.com>"]

keywords = ["ipld", "ipfs", "cid", "multihash"]

license = "MIT"

readme = "README.md"

[dependencies]
multihash = "~0.4.2"
multibase = "~0.4.0"
try_from = "~0.2.1"
varmint = "~0.1.2"
