[package]
name = "cid"
version = "0.5.1"
description = "CID in rust"
homepage = "https://github.com/multiformats/rust-cid"
authors = ["Friedel Ziegelmayer <dignifiedquire@gmail.com>"]
keywords = ["ipld", "ipfs", "cid", "multihash", "multiformats"]
license = "MIT"
readme = "README.md"
edition = "2018"

[package.metadata.release]
pre-release-commit-message = "Release {{version}} 🎉🎉"
no-dev-version = true

[features]
default = ["std"]
std = ["multibase", "multihash/std", "unsigned-varint/std"]
arb = ["quickcheck", "rand", "multihash/arb"]

[dependencies]
multihash = { version = "0.12", default-features = false }
unsigned-varint = { version = "0.5.1", default-features = false }

multibase = { version = "0.8.0", optional = true }
quickcheck = { version = "0.9.2", optional = true }
rand = { version = "0.7.3", optional = true }

[dev-dependencies]
quickcheck = "0.9.2"
rand = "0.7.3"
multihash = { version = "0.12", default-features = false, features = ["arb", "multihash-impl"] }
