[package]
name = "cid"
version = "0.5.1"
description = "CID in rust"
homepage = "https://github.com/multiformats/rust-cid"
authors = ["Friedel Ziegelmayer <dignifiedquire@gmail.com>"]
keywords = ["ipld", "ipfs", "cid", "multihash", "multiformats"]
license = "MIT"
readme = "README.md"
edition = "2018"

[package.metadata.release]
pre-release-commit-message = "Release {{version}} 🎉🎉"
no-dev-version = true

[features]
default = ["std"]
std = ["multibase", "multihash/std", "unsigned-varint/std"]
arb = ["quickcheck", "rand", "multihash/arb"]
scale-codec = ["parity-scale-codec", "multihash/scale-codec"]
serde-codec = ["serde", "multihash/serde-codec"]

[dependencies]
#multihash = "0.11.2"
#tiny_multihash = { path = "/home/vmx/src/pl/rust/tiny-multihash" }
#tiny_multihash = { }
#multihash = { package = "tiny-multihash", path = "/home/vmx/src/pl/rust/tiny-multihash" }
#multihash = { git = "https://github.com/multiformats/rust-multihash", branch = "merge-tiny-multihash" }
multihash = { path = "/home/vmx/src/pl/rust/rust-multihash", default-features = false, features = ["multihash-impl"] }
multibase = { version = "0.8.0", optional = true }
unsigned-varint = { version = "0.5.1", default-features = false }

parity-scale-codec = { version = "1.3.5", optional = true, default-features = false, features = ["derive"] }
quickcheck = { version = "0.9.2", optional = true }
rand = { version = "0.7.3", optional = true }
serde = { version = "1.0.116", optional = true }

[dev-dependencies]
quickcheck = "0.9.2"
rand = "0.7.3"
#multihash = { version = "0.11", features = ["test"] }
#multihash = { package = "tiny-multihash", features = ["test"], path = "/home/vmx/src/pl/rust/tiny-multihash" }
#multihash = { git = "https://github.com/multiformats/rust-multihash", branch = "merge-tiny-multihash", features = ["test"] }
multihash = { path = "/home/vmx/src/pl/rust/rust-multihash", default-features = false, features = ["arb"] }
serde_json = "1.0.59"
